### ISSUE TITLE
I am having an issue where depth seems to be reversed

### ISSUE THREAD

**Issue by RYRY1002** [XorDev/Ortho-Shaderpack#1]
I am using a modded version of the shader pack that I made. You can download it [here](https://github.com/XorDev/Ortho-Shaderpack/files/5849351/Ortho-Shaderpack-master.zip).
Its goal is to make the effect turn on and off depending on your `cameraPosition.x` coordinate.

Everything should be working just fine, but I cannot seem to fix this one bug. I am hoping that someone can help me fix it, thanks.

There are 2 screenshots below, one taken with the shader, and one without, both in the exact same spot.

![2021-01-21_23 43 36](https://user-images.githubusercontent.com/56659369/105353465-5e531700-5c43-11eb-8dc6-552a654f411a.png)
![2021-01-21_23 43 55](https://user-images.githubusercontent.com/56659369/105353477-64e18e80-5c43-11eb-9d11-04c65f8cc44f.png)

**Comment by XorDev** [comment]
Sorry, I'm quite busy and can't offer support on modified code. Maybe try multiplying the projection-space z-axis by -1.0.
Good luck!

**Comment by RYRY1002** [comment]
Ok that's fine, I fixed it anyways
